#!/usr/bin/env python3
"""
apply-settings.py
=================
Takes the upstream post-pve-install.sh and produces a customised version
with the user's pre-configured settings baked in (no interactive prompts
for those choices).

Usage: python3 apply-settings.py <upstream.sh> <output.sh>

Pre-configured as YES (auto-applied, no prompt):
  - Disable pve-enterprise repo  (PVE 8 & 9)
  - Enable pve-no-subscription    (PVE 8 & 9)
  - Correct Ceph package sources  (PVE 8 & 9)
  - Disable subscription nag
  - Disable High Availability + Corosync
  - apt update / dist-upgrade

Still prompted at runtime:
  - Correct PVE Sources (sources.list migration)
  - Reboot at the end
"""

import re
import sys

UPSTREAM_FILE = sys.argv[1] if len(sys.argv) > 1 else "upstream-latest.sh"
OUTPUT_FILE   = sys.argv[2] if len(sys.argv) > 2 else "post-pve-install.sh"

HEADER = '''\
#!/usr/bin/env bash

# ============================================================
#  CUSTOM FORK of community-scripts/ProxmoxVE post-pve-install
#  Upstream: https://github.com/community-scripts/ProxmoxVE
#
#  Pre-configured settings (auto-applied, no prompt):
#    ✓ Disable pve-enterprise repo
#    ✓ Enable pve-no-subscription repo
#    ✓ Correct Ceph package sources
#    ✓ Disable subscription nag
#    ✓ Disable High Availability
#    ✓ Run apt update/dist-upgrade
#
#  Settings still prompted (not forced):
#    - Correct PVE Sources (your choice at runtime)
#    - Reboot at the end
#
#  Maintained via GitHub Actions — auto-syncs with upstream.
#  DO NOT EDIT MANUALLY — re-generated by apply-settings.py
# ============================================================

'''

# ─── Patch catalogue ───────────────────────────────────────────────────────────
# Each entry is (description, search_pattern, replacement).
# Patterns match the whiptail CHOICE blocks we want to bypass.
# We replace the entire if/case block with a direct auto_* call.

PATCHES = [

    # ── PVE 8: pve-enterprise ── force "yes" branch ──────────────────────────
    (
        "PVE8: auto-disable pve-enterprise (skip whiptail)",
        r'(  CHOICE=\$\(whiptail[^\n]*PVE-ENTERPRISE[^\n]*\n(?:.*\n)*?  esac\n)',
        '''\
  # [CUSTOM] Auto-disable pve-enterprise repo
  msg_info "Disabling \'pve-enterprise\' repository"
  cat <<EOF >/etc/apt/sources.list.d/pve-enterprise.list
# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
EOF
  msg_ok "Disabled \'pve-enterprise\' repository"

''',
    ),

    # ── PVE 8: pve-no-subscription ── force "yes" ────────────────────────────
    (
        "PVE8: auto-enable pve-no-subscription (skip whiptail)",
        r'(  CHOICE=\$\(whiptail[^\n]*PVE-NO-SUBSCRIPTION[^\n]*\n(?:.*\n)*?  esac\n)',
        '''\
  # [CUSTOM] Auto-enable pve-no-subscription repo
  msg_info "Enabling \'pve-no-subscription\' repository"
  cat <<EOF >/etc/apt/sources.list.d/pve-install-repo.list
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
EOF
  msg_ok "Enabled \'pve-no-subscription\' repository"

''',
    ),

    # ── PVE 8: ceph sources ── force "yes" ───────────────────────────────────
    (
        "PVE8: auto-correct ceph sources (skip whiptail)",
        r'(  CHOICE=\$\(whiptail[^\n]*CEPH PACKAGE[^\n]*\n(?:.*\n)*?  esac\n)',
        '''\
  # [CUSTOM] Auto-correct ceph package sources
  msg_info "Correcting \'ceph package repositories\'"
  cat <<EOF >/etc/apt/sources.list.d/ceph.list
# deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
# deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
# deb https://enterprise.proxmox.com/debian/ceph-reef bookworm enterprise
# deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
EOF
  msg_ok "Corrected \'ceph package repositories\'"

''',
    ),

    # ── COMMON: subscription nag ── force "yes" ───────────────────────────────
    (
        "COMMON: auto-disable subscription nag (skip whiptail)",
        r'(  CHOICE=\$\(whiptail[^\n]*SUBSCRIPTION NAG[^\n]*\n(?:.*\n)*?  esac\n)',
        '''\
  # [CUSTOM] Auto-disable subscription nag
  msg_info "Disabling subscription nag"
  mkdir -p /usr/local/bin
  cat >/usr/local/bin/pve-remove-nag.sh <<\'NAGEOF\'
#!/bin/sh
WEB_JS=/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
if [ -s "$WEB_JS" ] && ! grep -q NoMoreNagging "$WEB_JS"; then
    sed -i -e "/data\\.status/ s/!//" -e "/data\\.status/ s/active/NoMoreNagging/" "$WEB_JS"
fi
NAGEOF
  chmod 755 /usr/local/bin/pve-remove-nag.sh
  cat >/etc/apt/apt.conf.d/no-nag-script <<\'APTEOF\'
DPkg::Post-Invoke { "/usr/local/bin/pve-remove-nag.sh"; };
APTEOF
  chmod 644 /etc/apt/apt.conf.d/no-nag-script
  msg_ok "Disabled subscription nag (clear browser cache after reboot)"

''',
    ),

    # ── COMMON: High Availability ── force "yes" to disable ──────────────────
    # The HA block has two nested whiptail calls (HA + Corosync). We collapse both.
    (
        "COMMON: auto-disable HA + Corosync (skip whiptail)",
        r'(  if systemctl is-active --quiet pve-ha-lrm.*?fi\n)',
        '''\
  # [CUSTOM] Auto-disable High Availability + Corosync
  if systemctl is-active --quiet pve-ha-lrm; then
    msg_info "Disabling high availability"
    systemctl disable -q --now pve-ha-lrm
    systemctl disable -q --now pve-ha-crm
    systemctl disable -q --now corosync 2>/dev/null || true
    msg_ok "Disabled High Availability + Corosync"
  else
    msg_ok "High availability already inactive — skipped"
  fi

''',
    ),

    # ── COMMON: apt update ── force "yes" ────────────────────────────────────
    (
        "COMMON: auto-run apt update/dist-upgrade (skip whiptail)",
        r'(  CHOICE=\$\(whiptail[^\n]*UPDATE[^\n]*\n(?:.*\n)*?  esac\n)',
        '''\
  # [CUSTOM] Auto-run system update
  msg_info "Updating Proxmox VE (this may take a while)"
  apt update &>/dev/null || msg_error "apt update failed"
  apt -y dist-upgrade &>/dev/null || msg_error "apt dist-upgrade failed"
  msg_ok "Updated Proxmox VE"

''',
    ),
]

# ── Future-version safety wrapper around main() ───────────────────────────────
FUTURE_VERSION_PATCH = (
    "Wrap unknown PVE major versions in main()",
    r'(  if \[\[ "\$PVE_MAJOR" == "8" \]\].*?fi\n)',
    '''\
  case "$PVE_MAJOR" in
  8) start_routines_8 ;;
  9) start_routines_9 ;;
  *)
    echo -e "\\033[33mWarning: PVE major version ${PVE_MAJOR} is newer than tested."
    echo -e "Applying common routines only. Check for script updates.\\033[m"
    post_routines_common
    ;;
  esac
''',
)

# ── Header banner tweak ───────────────────────────────────────────────────────
BANNER_PATCH = (
    "Add CUSTOM FORK label to banner",
    r'(EOF\n}\n)',
    'EOF\n  echo -e "\\n                    [ CUSTOM FORK - Auto-configured ]\\n"\n}\n',
    1,  # replace only first occurrence (the header_info EOF)
)


def apply_patch(content, description, pattern, replacement, count=0):
    """Apply a regex substitution. count=0 means replace all."""
    new_content, n = re.subn(pattern, replacement, content, count=count, flags=re.DOTALL)
    if n == 0:
        print(f"  ⚠  WARN: patch '{description}' matched nothing — upstream may have changed structure.")
    else:
        print(f"  ✓  Applied: {description} ({n} replacement(s))")
    return new_content


def main():
    print(f"Reading upstream: {UPSTREAM_FILE}")
    with open(UPSTREAM_FILE, "r") as f:
        content = f.read()

    # Strip shebang + original copyright block (we prepend our own header)
    content = re.sub(r'^#!/usr/bin/env bash\n', '', content)

    # Apply all patches
    print("\nApplying patches:")
    for patch in PATCHES:
        content = apply_patch(content, *patch)

    # Future-version safety
    content = apply_patch(content, *FUTURE_VERSION_PATCH)

    # Banner
    p = BANNER_PATCH
    content = apply_patch(content, p[0], p[1], p[2], count=p[3])

    # Prepend custom header
    output = HEADER + content

    with open(OUTPUT_FILE, "w") as f:
        f.write(output)

    print(f"\nOutput written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
